# Generated by Django 3.1.5 on 2021-02-04 15:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Контрагенты',
            },
        ),
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_date', models.DateField()),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='UOM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purch_date', models.DateField()),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('price_ex_vat', models.DecimalField(decimal_places=3, max_digits=10)),
                ('price_with_vat', models.DecimalField(decimal_places=3, max_digits=10)),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myfirstapp.counterparty')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myfirstapp.nomenclature')),
                ('purch_uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myfirstapp.uom')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionProduced',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('prod_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfirstapp.production')),
                ('produced', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myfirstapp.nomenclature')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionConsumed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('consumed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myfirstapp.nomenclature')),
                ('prod_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myfirstapp.production')),
            ],
        ),
        migrations.AddField(
            model_name='nomenclature',
            name='uom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myfirstapp.uom'),
        ),
        migrations.CreateModel(
            name='ConversionRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('base_uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='covn_base_uom', to='myfirstapp.uom')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='myfirstapp.nomenclature')),
                ('target_uom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='covn_target_uom', to='myfirstapp.uom')),
            ],
        ),
    ]
